// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgKTFBKcsO3AuYN8hHuU4gzKrxi1T_iiU',
    appId: '1:700306081623:android:6a684eb32ee0fe3b502012',
    messagingSenderId: '700306081623',
    projectId: 'teleseen-c42d9',
    databaseURL: 'https://teleseen-c42d9-default-rtdb.firebaseio.com',
    storageBucket: 'teleseen-c42d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDulK-3CVMO0RN6G7VrX_WzyXJPgEpEQsk',
    appId: '1:700306081623:ios:f57ec9ed00a379c1502012',
    messagingSenderId: '700306081623',
    projectId: 'teleseen-c42d9',
    databaseURL: 'https://teleseen-c42d9-default-rtdb.firebaseio.com',
    storageBucket: 'teleseen-c42d9.firebasestorage.app',
    androidClientId: '700306081623-l17otr2glduj7snf9g88g47mfr76j98u.apps.googleusercontent.com',
    iosClientId: '700306081623-6qnn0ttg8k6ordl613qds6n6bhaqqumo.apps.googleusercontent.com',
    iosBundleId: 'com.teleseen.webstore.ios',
  );
}
